name: findy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.2
  flutter_progress_hud: ^2.0.2
  connectivity_plus: ^6.0.0
  dio: 4.0.4
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.0 
  icons_plus: ^4.0.0
  flutter_downloader: ^1.11.4
  get: ^4.6.6
  flutter_easyloading: 3.0.3
  flutter_localizations:
    sdk: flutter
  syncfusion_localizations: ^20.4.54
  keyboard_dismisser: ^3.0.0
  another_flushbar: ^1.12.30
  logger: ^2.1.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  openpgp: ^3.7.3
  qr_code_scanner: ^1.0.1
  scan: ^1.6.0
  google_ml_kit: ^0.12.0
  camera: ^0.11.0
  dotted_border: ^2.1.0
  image: ^4.1.4
  web_socket_channel: ^2.4.3
  path: ^1.9.0
  path_provider: ^2.1.3
  date_picker_timeline: ^1.2.4
  table_calendar: ^3.0.6
  video_player: ^2.9.1
  syncfusion_flutter_charts: ^20.4.53
  syncfusion_flutter_calendar: ^20.4.50
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  primer_progress_bar: ^0.4.1
  flutter_secure_storage: ^9.2.2
  carousel_slider: ^4.2.1
  getwidget: ^4.0.0
  google_maps_flutter: ^2.6.1
  geolocator: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/file/
    - assets/videos/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/SFPRODISPLAYREGULAR.OTF
